spring:
  application:
    name: dept-provider-8001
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: dept-provider
        register-health-check: true
        health-check-path: /actuator/health
        health-check-interval: 30s
        health-check-timeout: 5s
        prefer-ip-address: true
        tags: version=2.2.20.0,environment=production
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://62.234.44.124:3306/consul_schema
    username: root
    password: 123456
  http:
    converters:
      preferred-json-mapper: gson #必须使用gson，否则健康检查会出错
  mvc:
    view:
      prefix: /templates
  thymeleaf:
    cache: false
    mode: HTML

server:
  port: 8001