server:
  port: 8500
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://62.234.44.124:3306/consul_schema
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    converters:
      preferred-json-mapper: gson #必须使用gson，否则健康检查会出错
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.yealink.entities
  configuration:
    map-underscore-to-camel-case: true
consul:
  debug-config:
    bind-address: 10.83.2.93
  config:
    node-name: myNode1
    datacenter: CN_DC1
